title: "Under the clouds | FWC"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # Options: air, aqua, contrast, dark, dirt, neon, sunrise

# Math Support (LaTeX)
markdown: kramdown
kramdown:
  math_engine: mathjax

# Collections for Hardware & Photography
collections:
  hardware:
    output: true
    permalink: /hardware/:path/
  photography:
    output: true
    permalink: /photography/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate

# Explicitly set the markdown engine for MathJax compatibility
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
