title: "The Azimuth"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

# Math Support
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

navigation:
  main: main

# Collections
collections:
  hardware:
    output: true
    permalink: /hardware/:path/
  photography:
    output: true
    permalink: /photography/:path/

# Global Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
      mathjax: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache  # <--- THIS IS THE FIX
  - jekyll-remote-theme

author:
  name   : "FWC"
  bio    : "Explorer"
  location: "SF Bay Area, California, USA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:1rjecixc5@mozmail.com"
      
minimal_mistakes_javascripts:
  - /assets/js/main.min.js